/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class appgrafos_JavaGrafos */

#ifndef _Included_appgrafos_JavaGrafos
#define _Included_appgrafos_JavaGrafos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     appgrafos_JavaGrafos
 * Method:    asignamientoSalas
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_appgrafos_JavaGrafos_asignamientoSalas
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
